language: python
sudo: required
dist: xenial
python:
  - 3.7
services:
  - postgresql
  - docker
install:
  - pip install poetry psycopg2
  - poetry config virtualenvs.create false --local
  - poetry install --no-dev --no-root --no-interaction --no-ansi
env:
  - SECRET_KEY='pipo' POSTGRES_PASSWORD='popi' POSTGRES_HOST=$(ip -4 addr show docker0 | grep -Po 'inet \K[\d.]+')
script:
  - docker build -t $TRAVIS_REPO_SLUG .
  - docker run --rm -e SECRET_KEY -e POSTGRES_PASSWORD -e POSTGRES_HOST -it $TRAVIS_REPO_SLUG ./manage.py migrate
  - docker run --rm -e SECRET_KEY -e POSTGRES_PASSWORD -e POSTGRES_HOST -it $TRAVIS_REPO_SLUG coverage run manage.py test
  - flake8 .
  - yapf -dr .
  - safety check
  - pip install "git+https://github.com/${TRAVIS_REPO_SLUG}.git#egg=djenealog"
after_success:
  - coveralls
