language: python
sudo: required
dist: xenial
python:
  - 3.6
services:
  - postgresql
  - docker
install:
  - pip install pipenv psycopg2 raven
  - pipenv install --deploy --dev
env:
  - SECRET_KEY='pipo' POSTGRES_PASSWORD='popi'
script:
  - docker build -t $TRAVIS_REPO_SLUG .
  - docker run --rm -e SECRET_KEY -e POSTGRES_PASSWORD -it $TRAVIS_REPO_SLUG ./manage.py migrate
  - docker run --rm -e SECRET_KEY -e POSTGRES_PASSWORD -it $TRAVIS_REPO_SLUG coverage run manage.py test
  - flake8 .
  - yapf -dr .
  - safety check
  - pip install "git+https://github.com/${TRAVIS_REPO_SLUG}.git#egg=djenealog"
after_success:
  - coveralls
