version: '3'

volumes:
  srv:
  sql:

services:
  postgres:
    image: postgres:10-alpine
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - "sql:/var/lib/postgresql/data"
  memcached:
    image: memcached:alpine
    restart: unless-stopped
  app:
    build: .
    restart: unless-stopped
    volumes:
      - "srv:/srv"
    env_file:
      - .env
    environment:
      - DB=postgres
      - MEMCACHED=True
    networks:
      - traefik
      - default
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host: djenealog.${DOMAIN_NAME:-local}"
      - "traefik.docker.network=traefik"
  nginx:
    image: nim65s/ndh:nginx
    restart: unless-stopped
    volumes:
      - "srv:/srv"
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host: djenealog.${DOMAIN_NAME:-local}; PathPrefix: /static, /media"

networks:
  traefik:
    external: true
