# Generated by Django 2.0.3 on 2018-03-25 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Couple',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gramps', models.PositiveSmallIntegerField(unique=True)),
                ('mariage_y', models.PositiveSmallIntegerField()),
                ('mariage_m', models.PositiveSmallIntegerField()),
                ('mariage_d', models.PositiveSmallIntegerField()),
                ('pacs', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Individu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gramps', models.PositiveSmallIntegerField(unique=True)),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('masculin', models.NullBooleanField()),
                ('naissance_y', models.PositiveSmallIntegerField()),
                ('naissance_m', models.PositiveSmallIntegerField()),
                ('naissance_d', models.PositiveSmallIntegerField()),
                ('deces_y', models.PositiveSmallIntegerField()),
                ('deces_m', models.PositiveSmallIntegerField()),
                ('deces_d', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Lieu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gramps', models.PositiveSmallIntegerField(unique=True)),
                ('nom', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='individu',
            name='deces',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='djenealog.Lieu'),
        ),
        migrations.AddField(
            model_name='individu',
            name='naissance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='djenealog.Lieu'),
        ),
        migrations.AddField(
            model_name='individu',
            name='parents',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='djenealog.Couple'),
        ),
        migrations.AddField(
            model_name='couple',
            name='femme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mere', to='djenealog.Individu'),
        ),
        migrations.AddField(
            model_name='couple',
            name='mari',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pere', to='djenealog.Individu'),
        ),
        migrations.AddField(
            model_name='couple',
            name='mariage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='djenealog.Lieu'),
        ),
    ]
