# Generated by Django 3.0.6 on 2020-05-26 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("djenealog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="lieu",
            options={"ordering": ["name"], "verbose_name_plural": "Lieux"},
        ),
    ]
