# Generated by Django 2.0.3 on 2018-03-25 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djenealog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='couple',
            name='gramps',
        ),
        migrations.RemoveField(
            model_name='individu',
            name='gramps',
        ),
        migrations.RemoveField(
            model_name='lieu',
            name='gramps',
        ),
        migrations.AlterField(
            model_name='individu',
            name='parents',
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.PROTECT, related_name='enfants', to='djenealog.Couple'),
        ),
    ]
