# Generated by Django 3.1 on 2020-08-09 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djenealog", "0002_order_lieux"),
    ]

    operations = [
        migrations.AlterField(
            model_name="individu",
            name="masculin",
            field=models.BooleanField(null=True),
        ),
    ]
