# Generated by Django 2.0.3 on 2018-03-25 22:43

from django.db import migrations, models
import django.db.models.deletion


def migrate_events(apps, schema_editor):
    Individu, Couple, Naissance, Deces, Mariage = (apps.get_model('djenealog', model)
                                                   for model in ('Individu', 'Couple', 'Naissance', 'Deces',
                                                                 'Mariage'))
    for individu in Individu.objects.all():
        if individu.naissance_y:
            Naissance.objects.create(individu=individu,
                                     lieu=individu.naissance.nom if individu.naissance else None,
                                     y=individu.naissance_y or None,
                                     m=individu.naissance_m or None,
                                     d=individu.naissance_d or None)
        if individu.deces_y:
            Deces.objects.create(individu=individu,
                                 lieu=individu.deces.nom if individu.deces else None,
                                 y=individu.deces_y or None,
                                 m=individu.deces_m or None,
                                 d=individu.deces_d or None)
    for couple in Couple.objects.all():
        if couple.mariage_y:
            Mariage.objects.create(couple=couple,
                                   lieu=couple.mariage.nom if couple.mariage else None,
                                   y=couple.mariage_y or None,
                                   m=couple.mariage_m or None,
                                   d=couple.mariage_d or None)


class Migration(migrations.Migration):

    dependencies = [
        ('djenealog', '0002_auto_20180326_0038'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bapteme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lieu', models.CharField(blank=True, max_length=50, null=True)),
                ('y', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('m', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('d', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('individu',
                 models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,
                                   related_name='b',
                                   to='djenealog.Individu')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Deces',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lieu', models.CharField(blank=True, max_length=50, null=True)),
                ('y', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('m', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('d', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('individu',
                 models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,
                                   related_name='d',
                                   to='djenealog.Individu')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Mariage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lieu', models.CharField(blank=True, max_length=50, null=True)),
                ('y', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('m', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('d', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Naissance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lieu', models.CharField(blank=True, max_length=50, null=True)),
                ('y', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('m', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('d', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('individu',
                 models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,
                                   related_name='n',
                                   to='djenealog.Individu')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Pacs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lieu', models.CharField(blank=True, max_length=50, null=True)),
                ('y', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('m', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('d', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='couple',
            name='pacs',
        ),
        migrations.AddField(
            model_name='pacs',
            name='couple',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,
                                    related_name='p',
                                    to='djenealog.Couple'),
        ),
        migrations.AddField(
            model_name='mariage',
            name='couple',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,
                                    related_name='m',
                                    to='djenealog.Couple'),
        ),
        migrations.RunPython(migrate_events),
    ]
