# Generated by Django 4.1.7 on 2023-03-12 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djenealog', '0003_nullbooleanfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individu',
            name='epouse',
            field=models.CharField(blank=True, max_length=50, verbose_name='Nom d`épouse ou d`usage'),
        ),
        migrations.AlterField(
            model_name='individu',
            name='usage',
            field=models.CharField(blank=True, max_length=50, verbose_name='Prénom d`usage'),
        ),
        migrations.AlterField(
            model_name='lieu',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='name'),
        ),
    ]
