# Generated by Django 2.0.3 on 2018-03-25 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djenealog', '0003_auto_20180326_0043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='couple',
            name='mariage',
        ),
        migrations.RemoveField(
            model_name='couple',
            name='mariage_d',
        ),
        migrations.RemoveField(
            model_name='couple',
            name='mariage_m',
        ),
        migrations.RemoveField(
            model_name='couple',
            name='mariage_y',
        ),
        migrations.RemoveField(
            model_name='individu',
            name='deces',
        ),
        migrations.RemoveField(
            model_name='individu',
            name='deces_d',
        ),
        migrations.RemoveField(
            model_name='individu',
            name='deces_m',
        ),
        migrations.RemoveField(
            model_name='individu',
            name='deces_y',
        ),
        migrations.RemoveField(
            model_name='individu',
            name='naissance',
        ),
        migrations.RemoveField(
            model_name='individu',
            name='naissance_d',
        ),
        migrations.RemoveField(
            model_name='individu',
            name='naissance_m',
        ),
        migrations.RemoveField(
            model_name='individu',
            name='naissance_y',
        ),
        migrations.AlterField(
            model_name='bapteme',
            name='individu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='djenealog.Individu'),
        ),
        migrations.AlterField(
            model_name='deces',
            name='individu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='djenealog.Individu'),
        ),
        migrations.AlterField(
            model_name='mariage',
            name='couple',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='djenealog.Couple'),
        ),
        migrations.AlterField(
            model_name='naissance',
            name='individu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='djenealog.Individu'),
        ),
        migrations.AlterField(
            model_name='pacs',
            name='couple',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='djenealog.Couple'),
        ),
    ]
