# Generated by Django 2.0.3 on 2018-03-25 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djenealog', '0004_auto_20180326_0052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bapteme',
            name='individu',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='djenealog.Individu'),
        ),
        migrations.AlterField(
            model_name='deces',
            name='individu',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='djenealog.Individu'),
        ),
        migrations.AlterField(
            model_name='mariage',
            name='couple',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='djenealog.Couple'),
        ),
        migrations.AlterField(
            model_name='naissance',
            name='individu',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='djenealog.Individu'),
        ),
        migrations.AlterField(
            model_name='pacs',
            name='couple',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='djenealog.Couple'),
        ),
    ]
