# Generated by Django 2.0.3 on 2018-03-25 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djenealog', '0005_auto_20180326_0053'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lieu',
        ),
    ]
