# Generated by Django 2.0.3 on 2018-03-26 00:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djenealog', '0006_delete_lieu'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bapteme',
            old_name='individu',
            new_name='inst',
        ),
        migrations.RenameField(
            model_name='deces',
            old_name='individu',
            new_name='inst',
        ),
        migrations.RenameField(
            model_name='mariage',
            old_name='couple',
            new_name='inst',
        ),
        migrations.RenameField(
            model_name='naissance',
            old_name='individu',
            new_name='inst',
        ),
        migrations.RenameField(
            model_name='pacs',
            old_name='couple',
            new_name='inst',
        ),
        migrations.AlterField(
            model_name='bapteme',
            name='d',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='jour'),
        ),
        migrations.AlterField(
            model_name='bapteme',
            name='m',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='mois'),
        ),
        migrations.AlterField(
            model_name='bapteme',
            name='y',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='année'),
        ),
        migrations.AlterField(
            model_name='couple',
            name='femme',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='mere',
                to='djenealog.Individu'),
        ),
        migrations.AlterField(
            model_name='couple',
            name='mari',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='pere',
                to='djenealog.Individu'),
        ),
        migrations.AlterField(
            model_name='deces',
            name='d',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='jour'),
        ),
        migrations.AlterField(
            model_name='deces',
            name='m',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='mois'),
        ),
        migrations.AlterField(
            model_name='deces',
            name='y',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='année'),
        ),
        migrations.AlterField(
            model_name='individu',
            name='parents',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='enfants',
                to='djenealog.Couple'),
        ),
        migrations.AlterField(
            model_name='mariage',
            name='d',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='jour'),
        ),
        migrations.AlterField(
            model_name='mariage',
            name='m',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='mois'),
        ),
        migrations.AlterField(
            model_name='mariage',
            name='y',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='année'),
        ),
        migrations.AlterField(
            model_name='naissance',
            name='d',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='jour'),
        ),
        migrations.AlterField(
            model_name='naissance',
            name='m',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='mois'),
        ),
        migrations.AlterField(
            model_name='naissance',
            name='y',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='année'),
        ),
        migrations.AlterField(
            model_name='pacs',
            name='d',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='jour'),
        ),
        migrations.AlterField(
            model_name='pacs',
            name='m',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='mois'),
        ),
        migrations.AlterField(
            model_name='pacs',
            name='y',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='année'),
        ),
    ]
