# Generated by Django 2.0.3 on 2018-03-27 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djenealog', '0007_auto_20180326_0240'),
    ]

    operations = [
        migrations.AddField(
            model_name='individu',
            name='epouse',
            field=models.CharField(blank=True, max_length=50, verbose_name='épouse'),
        ),
        migrations.AlterField(
            model_name='couple',
            name='femme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='femme', to='djenealog.Individu'),
        ),
        migrations.AlterField(
            model_name='couple',
            name='mari',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mari', to='djenealog.Individu'),
        ),
        migrations.AlterField(
            model_name='individu',
            name='nom',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='individu',
            name='prenom',
            field=models.CharField(blank=True, max_length=50, verbose_name='prénom'),
        ),
    ]
