# Generated by Django 2.0.3 on 2018-04-01 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djenealog', '0008_auto_20180328_0114'),
    ]

    operations = [
        migrations.AddField(
            model_name='individu',
            name='usage',
            field=models.CharField(blank=True, max_length=50, verbose_name='Prénom d’usage'),
        ),
        migrations.AlterField(
            model_name='individu',
            name='epouse',
            field=models.CharField(blank=True, max_length=50, verbose_name='Nom d’épouse ou d’usage'),
        ),
        migrations.AlterField(
            model_name='individu',
            name='prenom',
            field=models.CharField(blank=True, max_length=50, verbose_name='Prénom'),
        ),
    ]
