# Generated by Django 2.0.3 on 2018-04-02 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djenealog', '0008_auto_20180328_0114'),
    ]

    operations = [
        migrations.AddField(
            model_name='individu',
            name='wikidata',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
