# Generated by Django 2.0.3 on 2018-04-05 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djenealog', '0009_individu_wikidata'),
        ('djenealog', '0010_divorce'),
    ]

    operations = [
    ]
