# Generated by Django 2.0.3 on 2018-04-05 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djenealog', '0011_merge_20180405_2048'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bapteme',
            options={'verbose_name': 'baptême'},
        ),
        migrations.AlterModelOptions(
            name='deces',
            options={
                'verbose_name': 'décès',
                'verbose_name_plural': 'décès'
            },
        ),
        migrations.AlterModelOptions(
            name='pacs',
            options={'verbose_name_plural': 'pacs'},
        ),
    ]
