# Generated by Django 2.0.4 on 2018-04-05 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djenealog', '0012_auto_20180405_2225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bapteme',
            name='inst',
        ),
        migrations.DeleteModel(
            name='Bapteme',
        ),
    ]
