# Generated by Django 2.0.5 on 2018-05-20 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djenealog', '0013_auto_20180405_2234'),
    ]

    operations = [
        migrations.AddField(
            model_name='couple',
            name='debut',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='couple',
            name='fin',
            field=models.DateField(blank=True, null=True),
        ),
    ]
