# Generated by Django 2.2.4 on 2019-08-09 16:32

import autoslug.fields
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import ndh.models


class Migration(migrations.Migration):

    dependencies = [
        ('djenealog', '0015_commentaires'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lieu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True)),
                ('wikidata', models.PositiveIntegerField(blank=True, null=True)),
                ('point',
                 django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326)),
            ],
            options={
                'abstract': False,
            },
            bases=(ndh.models.Links, models.Model),
        ),
    ]
