# Generated by Django 2.2.4 on 2019-08-09 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djenealog', '0016_lieu'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lieu',
            options={'verbose_name_plural': 'Lieux'},
        ),
    ]
