# Generated by Django 2.2.4 on 2019-08-09 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djenealog', '0017_lieux'),
    ]

    operations = [
        migrations.AddField(
            model_name='deces',
            name='new_lieux',
            field=models.ForeignKey(blank=True,
                                    null=True,
                                    on_delete=django.db.models.deletion.PROTECT,
                                    to='djenealog.Lieu'),
        ),
        migrations.AddField(
            model_name='divorce',
            name='new_lieux',
            field=models.ForeignKey(blank=True,
                                    null=True,
                                    on_delete=django.db.models.deletion.PROTECT,
                                    to='djenealog.Lieu'),
        ),
        migrations.AddField(
            model_name='mariage',
            name='new_lieux',
            field=models.ForeignKey(blank=True,
                                    null=True,
                                    on_delete=django.db.models.deletion.PROTECT,
                                    to='djenealog.Lieu'),
        ),
        migrations.AddField(
            model_name='naissance',
            name='new_lieux',
            field=models.ForeignKey(blank=True,
                                    null=True,
                                    on_delete=django.db.models.deletion.PROTECT,
                                    to='djenealog.Lieu'),
        ),
        migrations.AddField(
            model_name='pacs',
            name='new_lieux',
            field=models.ForeignKey(blank=True,
                                    null=True,
                                    on_delete=django.db.models.deletion.PROTECT,
                                    to='djenealog.Lieu'),
        ),
    ]
