# Generated by Django 2.2.4 on 2019-08-09 17:26

from django.db import migrations

lieux = {
    '33500 St Loubès': 201784,
    '33560 Ste Eulalie': 736202,
    'Agen': 6625,
    'Antagnac': 663769,
    'Arcachon': 191460,
    'Aude': 3207,
    'Belesta': 629760,
    'Belin-Béliet': 243891,
    'Blois': 160927,
    'Boffres': 326692,
    'Bordeaux': 1479,
    'Boulogne sur mer': 81997,
    'Bourges': 132404,
    'Cahors': 23047,
    'Casteljaloux': 494589,
    'Caussade': 839648,
    'Cenon': 1053472,
    'Cestas': 326520,
    'Chatillon sur Seine': 244707,
    'Chomérac': 840132,
    'Clermont-Ferrand': 42168,
    'Estirac': 1092771,
    'Floirac': 199682,
    'Gourdon': 175525,
    'Herry': 1422864,
    'Ivry sur Seine': 193877,
    'La Rochelle': 82185,
    'La Teste de Buch': 233133,
    'Labastide Castel-amouroux': 1104360,
    'Lafitte sur Lot': 579024,
    'Langeais': 28335215,
    'Langon': 207154,
    'Lettonie': 211,
    'Liac': 1326265,
    'Marmande': 210742,
    'Montpouillan': 1104449,
    'Mérignac': 205551,
    'Méry-és-Bois': 1173595,
    'Nantes': 12191,
    'Neufmoutier-en-brie': 1459717,
    'Noaillan': 1007331,
    'Pamiers': 209834,
    'Papeete': 130800,
    'Paris': 90,
    'Port au Prince': 34261,
    'Poussignac': 194456,
    'Pradettes': 1376267,
    'Privas': 193060,
    'Razac-sur-Lisle': 1076734,
    'Ris-Orangis': 274237,
    'Rochefor sur mer': 207587,
    'Roquefixade': 816923,
    'Roussillon, Isère': 632191,
    'Rufiac': 220156,
    'Sainte Gemme': 1007267,
    'Samazan': 1105184,
    'Samer': 74641,
    'Samméjan': 218546,
    'Seyches': 1105208,
    'St Loubes': 201784,
    'St Loubès': 201784,
    'St Projet': 368477,
    'Séron': 1323438,
    'Tonneins': 1070001,
    'Toulouse': 7880,
    'Tulle': 157713,
    'Tulles': 157713,
    'Valence': 1467944,
    'Venise': 641,
    'Verfeil sur Seye': 1429508,
    'Vic Bigorre': 1324316,
    "faa'a": 1022934,
}


def populate_lieux(apps, schema_editor):
    Lieu = apps.get_model('djenealog', 'Lieu')
    for name, wikidata in lieux.items():
        Lieu.objects.get_or_create(wikidata=wikidata, defaults={'name': name})


class Migration(migrations.Migration):

    dependencies = [
        ('djenealog', '0017_lieux'),
    ]

    operations = [
        migrations.RunPython(populate_lieux),
    ]
