# Generated by Django 2.2.4 on 2019-08-09 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djenealog', '0018_evenements_lieux'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deces',
            name='lieu',
        ),
        migrations.RemoveField(
            model_name='divorce',
            name='lieu',
        ),
        migrations.RemoveField(
            model_name='mariage',
            name='lieu',
        ),
        migrations.RemoveField(
            model_name='naissance',
            name='lieu',
        ),
        migrations.RemoveField(
            model_name='pacs',
            name='lieu',
        ),
    ]
