# Generated by Django 2.2.4 on 2019-08-09 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djenealog', '0019_drop_old_lieu'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deces',
            old_name='new_lieux',
            new_name='lieu',
        ),
        migrations.RenameField(
            model_name='divorce',
            old_name='new_lieux',
            new_name='lieu',
        ),
        migrations.RenameField(
            model_name='mariage',
            old_name='new_lieux',
            new_name='lieu',
        ),
        migrations.RenameField(
            model_name='naissance',
            old_name='new_lieux',
            new_name='lieu',
        ),
        migrations.RenameField(
            model_name='pacs',
            old_name='new_lieux',
            new_name='lieu',
        ),
    ]
