name: docker
on: push
jobs:
  docker:
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: 1
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Configure
        run: echo -e "SECRET_KEY=pipo\nPOSTGRES_PASSWORD=popi" > .env
      - name: Network
        run: docker network create web
      - name: Start
        run: docker-compose up -d
      - name: Test
        run: docker-compose run djenealog poetry run ./manage.py test
