name: build docker image and run tests inside
on: [push]
jobs:
  docker:
    runs-on: ubuntu-latest
    env:
      SECRET_KEY: "pipo"
      POSTGRES_PASSWORD: "popi"
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: "popi"
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build
        uses: docker/build-push-action@v2
        with:
          tags: ${{ github.repository}}
          load: true
      -
        name: Migrate
        run: docker run --rm -e SECRET_KEY -e POSTGRES_PASSWORD -t ${{ github.repository}} poetry run ./manage.py migrate
      -
        name: Test
        run: docker run --rm -e SECRET_KEY -e POSTGRES_PASSWORD -t ${{ github.repository}} poetry run ./manage.py test
